Table
nobu9232/chat-space pull request #1
Opened 2019-04-06 10:40 UTC by nobu9232

# WHAT
README.mdChatSpaceのデータベース設計を記述

# WHY
ChatSpaceカリキュラムに必要なため

2019-04-06 11:15 UTC, kuroko918 commented on README.md
> +|timestamps|
timestampsはデフォルトではいるので明記しなくて大丈夫です。
他の部分も修正お願いします。

2019-04-06 11:15 UTC, kuroko918 commented on README.md
> +- has_many :groups, through: :members
ここ2行重複してしまっています。

2019-04-06 11:15 UTC, kuroko918 commented on README.md
> +- belongs_to :user
これはどちらですか？belongs_to userでhas_many :usersということはないです。

2019-04-07 03:55 UTC, nobu9232 commented on README.md
> +- has_many :groups, through: :members
重複箇所を修正しました。

2019-04-07 03:55 UTC, nobu9232 commented on README.md
> +- belongs_to :user
has_many :usersに変更しました。

2019-04-07 03:58 UTC, yuki-uchida requested changes

2019-04-07 03:58 UTC, yuki-uchida commented on README.md
> +|user_id|integer|
外部キー制約をつけ、typeはrefference型としましょう

2019-04-07 03:58 UTC, yuki-uchida commented on README.md
> +|user_id|integer|
こちらも

2019-04-07 03:58 UTC, yuki-uchida commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
こちらも

2019-04-07 04:57 UTC, nobu9232 commented on README.md
> +|user_id|integer|
外部キー制約をつけました。

2019-04-07 04:57 UTC, nobu9232 commented on README.md
> +|user_id|integer|
外部キー制約をつけました。

2019-04-07 04:57 UTC, nobu9232 commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
外部キー制約をつけました。

2019-04-07 05:01 UTC, ghost requested changes

2019-04-07 05:01 UTC, hiroki5123 commented on README.md
> +|group_id|integer|
これ必要ありません

2019-04-07 05:01 UTC, hiroki5123 commented on README.md
> +### association
アソシエーションが１つ足りないので見直してみましょう

2019-04-07 05:01 UTC, hiroki5123 commented on README.md
> +- has_many :users, through: :members
アソシエーションが２つ足りないので見直してみましょう

2019-04-07 05:01 UTC, hiroki5123 commented on README.md
> +|user|refference|foreign_key: true|
referencesですね

2019-04-07 05:01 UTC, hiroki5123 commented on README.md
> +### association
アソシエーションが１つ足りません

2019-04-07 05:01 UTC, hiroki5123 commented on README.md
> +## messagesテーブル
カラムが１つ足りません

2019-04-07 05:35 UTC, nobu9232 commented on README.md
> +|group_id|integer|
修正しました。

2019-04-07 05:35 UTC, nobu9232 commented on README.md
> +### association
追加しました。

2019-04-07 05:35 UTC, nobu9232 commented on README.md
> +- has_many :users, through: :members
追加しました。

2019-04-07 05:36 UTC, nobu9232 commented on README.md
> +|user|refference|foreign_key: true|
修正しました。

2019-04-07 05:36 UTC, nobu9232 commented on README.md
> +### association
追加しました。

2019-04-07 05:36 UTC, nobu9232 commented on README.md
> +## messagesテーブル
追加しました。

2019-04-07 06:06 UTC, ghost requested changes

2019-04-07 06:06 UTC, hiroki5123 commented on README.md
> +|message|text|nul: false|
ここtextというカラム名の方がいいかと思います

2019-04-07 06:06 UTC, hiroki5123 commented on README.md
> +|message|text|nul: false|
画像だけでも送れるようにしたいので、not null制約外しましょう

2019-04-07 06:14 UTC, nobu9232 commented on README.md
> +|message|text|nul: false|
カラム名をmessage→textに変更して、
画像だけでも送れるようにnot null制約外しました。

2019-04-07 06:15 UTC, ghost approved these changes
LGTMです！

2019-04-07 06:41 UTC, merged